# Generated by Django 6.0.1 on 2026-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='societyexpense',
            options={'verbose_name_plural': 'Society Expenses'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending Verification'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
