# Generated by Django 6.0.1 on 2026-04-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_admin_facility_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='booking_fee',
            new_name='fee',
        ),
        migrations.AddField(
            model_name='facility',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
