# Generated by Django 6.0.1 on 2026-04-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_rename_booking_fee_facility_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
    ]
