# Generated by Django 6.0.1 on 2026-04-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
